---
version: '3.9'
services:
  kafka:
    image: wurstmeister/kafka
    depends_on: 
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "example:3:1,web_requests:3:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    healthcheck:
      test: ["CMD", "bash", "-c", "unset", "JMX_PORT", ";", "kafka-topics.sh", "--zookeeper", "zookeeper:2181", "--list"]

  zookeeper:
    image: wurstmeister/zookeeper
    privileged: true
    ports:
      - 2181:2181

  localstack:
    image: localstack/localstack
    ports: 
      - 4566:4566
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/health" ]

  statsd:
    image: graphiteapp/graphite-statsd
    ports:
      - 80:80
      - 2003:2003
      - 2004:2004
      - 2023:2023
      - 2024:2024
      - 8125:8125/udp
      - 8126:8126

  setup:
    image: localstack/localstack  
    depends_on: 
      - kafka
      - localstack
    entrypoint: "/bin/bash"
    command:
      - /localstack-create_dynamodb_test_tables.sh
    volumes:
      - "./bin/localstack-create_dynamodb_test_tables.sh:/localstack-create_dynamodb_test_tables.sh"

