FROM python:3.10-alpine

RUN apk add --no-cache bash openssh ca-certificates jq curl openssl perl git zip \
 && apk add --no-cache --virtual .build-deps gcc make openssl-dev libffi-dev musl-dev linux-headers \
 && apk add --no-cache libintl icu-libs libc6-compat \
 && apk add --no-cache bash-completion \
 && update-ca-certificates
RUN pip3 install azure-cli
RUN pip3 install awscli
RUN az config set extension.use_dynamic_install=yes_without_prompt

ENTRYPOINT ["/bin/bash"]